apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
jobs:
  xygeni-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v3.2.0
        id: Xygeni-Scanner
        with:
          xygeni_url: https://api.xygeni.io
          token: ${{ secrets.XYGENI_TOKEN }}
          gh_token: ${{ secrets.PAT_FOR_XYGENI_SCAN }}
on:
  workflow_dispatch:
