apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: xygeni-scan

on:
  workflow_dispatch: {}

jobs:
  xygeni-scan:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        with:
          fetch-depth: 0

      - name: Download + unzip Xygeni Scanner + run scan (no docker scanner)
        uses: docker://maven:3.9.9-eclipse-temurin-17
        env:
          XYGENI_URL: "https://api.xygeni.io"
          XYGENI_TOKEN: ${{ secrets.XYGENI_TOKEN }}
        run: |
          set -euo pipefail

          echo "== Verify required tools =="
          command -v mvn >/dev/null 2>&1 || (echo "mvn not found" && exit 1)

          # Ensure curl + unzip exist (image is Debian-based)
          if ! command -v curl >/dev/null 2>&1 || ! command -v unzip >/dev/null 2>&1; then
            apt-get update
            apt-get install -y curl unzip ca-certificates
          fi

          echo "== Download scanner zip =="
          curl -sSL -o xygeni-release.zip https://get.xygeni.io/latest/scanner/xygeni-release.zip

          echo "== Unzip =="
          rm -rf xygeni-scanner
          unzip -q xygeni-release.zip
          ls xygeni-scanner/

          echo "== Locate xygeni binary and run =="
          # Ajusta esta ruta si tu zip trae otro nombre exacto de carpeta
          chmod +x xygeni-scanner/xygeni

          xygeni-scanner/xygeni \
            --url "${XYGENI_URL}" \
            --token "${XYGENI_TOKEN}" \
            scan --never-fail -n "${CLOUDBEES_REPO:-repo}" -d .
